#!/bin/sh
xrandr --output HDMI-0 --mode 3840x2160 --pos 0x0 --rotate normal --output DP-0 --primary --mode 3840x2160 --rotate normal --output DVI-I-1 --off --output DVI-I-0 --off --output DP-1 --off --output DVI-D-0 --off
