set modelines=1
" Color {{{
set t_Co=256			" Enable 256 color mode
:colorscheme monokai " Set colorscheme
syntax enable			" Enable syntax processing
" }}}

" Spaces & Tabs {{{
set tabstop=4			" Number of visual spaces per TAB
set softtabstop=4		" Number of spaces in TAB when editing
set expandtab			" TAB -> Space
set shiftwidth=4		" indenting uses 4 spaces
" }}}

" UI Config {{{
set number			" Show line numbers
set relativenumber  " Show relative line numbers
set showcmd			" Show last command in bottom bar
set cursorline		" Highlight current line

set colorcolumn=100	" Show column at line character limit

highlight ColorColumn ctermbg=darkgrey

filetype indent on	" Load file type-specific indent files

set wildmenu		" Visual Autocomplete for command menu

set lazyredraw		" Redraw only when necessary

set showmatch		" Highlight matching parenthesis

set splitright		" Open new vertical split to the right

set scrolloff=20    " Try to keep 20 lines up/down from the current line in the display
" }}}

" Searching {{{
set incsearch		" Search as characters are entered
set hlsearch		" Highlight search matches

" }}}

"Remappings {{{
" Turn off search highlight
nnoremap <C-x> :nohlsearch<CR>
" Switch between relative and absolut line numbers
nnoremap <NUL> :call NumberToggle()<CR>
" space open/closes folds
" Movement {{{
" Remap buffer switching
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Remap movement for wrapped lines
nnoremap j gj
nnoremap k gk
" }}}
nnoremap <space> za
" }}}

" Commands {{{
command Term vert term++close
" }}}

" Folding {{{
set foldenable		" enable folding
set foldlevelstart=10 " open folds up to x levels
set foldnestmax=10	" Max x nested folds
set foldmethod=indent	" fold based on indent level in python
" }}}

" Language Specifics {{{
" C {{{
autocmd FileType c set foldmethod=syntax	" fold based on syntax in c
" }}}
" Python{{{
autocmd FileType c set foldmethod=indent " fold based on syntax in c
" }}}
" LaTex {{{
autocmd FileType tex hi clear SpellBad  " Clear current spellBad highlighting
autocmd FileType tex hi SpellBad cterm=underline ctermfg=red  " Use a red underline for highlighting
autocmd FileType tex setlocal spell spelllang=en_us " Use english spell checking in tex files

autocmd FileType tex set textwidth=100
autocmd FileType tex set wrap linebreak nolist
" }}}
" }}}

" Custom Functions {{{
" Switch relative/absolute line numbers
func! NumberToggle()
	if(&relativenumber == 1)
        set number
        set norelativenumber
    else
        set nonumber
        set relativenumber
    endif
endfunc

" }}}

" Misc {{{
set clipboard=unnamedplus	" Set global clipboard
set encoding=utf-8		    " Set encoding to utf-8

set backup				    " Enable backup
set backupdir=~/.vim/backup " Set Backup directory
set directory=~/.vim/tmp	" Set .swp directory
" }}}

" Plugins {{{
" Vundle plugin
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
" vim fugitive {{{
Plugin 'tpope/vim-fugitive'
" }}}
" Air Line {{{
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
let g:airlinie#extensions#branch#enable=1
let g:airline_powerline_fonts=1
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
" }}}
" fzf {{{
Plugin 'junegunn/fzf', { 'do': { -> fzf#install() }}
Plugin 'junegunn/fzf.vim'
nnoremap <C-g> :Rg<Cr>
" }}}
" Vim Wiki {{{
Plugin 'vimwiki/vimwiki'
let wiki = {}
let wiki.nested_syntaxes = {'python' : 'python', 'c' : 'c'} " Activate syntax highlighting in vimwiki
let g:vimwiki_list=[{'path' : '~/Documents/vimwiki', 'path_html' : '~/Documents/vimwiki/html_out'}]
" }}}
" Coc {{{
Plugin 'neoclide/coc.nvim', {'branch': 'release'} " IntelSense Engine for Vim
" Mappings {{{
nnoremap gd :call CocActionAsync('jumpDefinition', 'tab drop')<CR>
nnoremap gr :call CocActionAsync('jumpReferences', 'tab drop')<CR>
nnoremap gi :call CocActionAsync('jumpImplementation', 'tab drop')<CR>
" }}}
" }}}
" Rust {{{
Plugin 'rust-lang/rust.vim'
" }}}
call vundle#end()
filetype plugin indent on
" Vundle plugin end

" }}}

" Startup {{{
" }}}
" vim:foldmethod=marker:foldlevel=0
